apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-app
  labels:
    name: analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics-app
  template:
    metadata:
      labels:
        service: analytics-app
    spec:
      containers:
      - name: analytics-app
        image: 547318948247.dkr.ecr.us-east-1.amazonaws.com/coworking-space-microservice:8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5050
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
              
      restartPolicy: Always