apiVersion: v1
kind: Service
metadata:
  name: analytics-app
spec:
  selector:
    app.kubernetes.io/name: analytics-app
  ports:
  - name: "5050"
    protocol: TCP
    port: 5050
    targetPort: 5050
